### ISSUE TITLE
Release 59348 and above not fully backward compatible (GLibC) 

### ISSUE THREAD

**Issue by YoannVarquet** [yoctopuce/yoctolib_python#9] opened 2024-02-20 09:20 UTC
Hi, 

I installed an older version through pip3 a one of my system, and it works great, (awesome job!), however, since New API, 2.0, the DLL are not compatible with my system. I use Nvidia with an old JetPack and can't move from it, and I get an GlibC imcompatibility issue. Having a lot of things running on it, I cannot just afford to upgrade GlibC, way too much hassle. 

```
Traceback (most recent call last):

  File "/home/nvidia/ws/scripts/gpio_control_yocto.py", line 711, in <module>
    node = GPIOControl()
  File "/home/nvidia/ws/scripts/gpio_control_yocto.py", line 141, in __init__
    self.init_pwm()
  File "/home/nvidia/ws/scripts/gpio_control_yocto.py", line 238, in init_pwm
    if YAPI.RegisterHub("usb", errmsg) != YAPI.SUCCESS:
  File "/home/nvidia/.local/lib/python3.6/site-packages/yoctopuce/yocto_api.py", line 2652, in RegisterHub
    res = YAPI.InitAPI(0, errmsg)
  File "/home/nvidia/.local/lib/python3.6/site-packages/yoctopuce/yocto_api.py", line 2520, in InitAPI
    YAPI.yloadYapiCDLL()
  File "/home/nvidia/.local/lib/python3.6/site-packages/yoctopuce/yocto_api.py", line 1207, in yloadYapiCDLL
    "): " + str(ex))
ImportError: Unable to import YAPI shared library (/home/nvidia/.local/lib/python3.6/site-packages/yoctopuce/cdll/libyapi-aarch64.so): /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/nvidia/.local/lib/python3.6/site-packages/yoctopuce/cdll/libyapi-aarch64.so)
```

Current GlibC is 2.27.

I guess I'll be installing Yoctopuce from source, but it would be nice to have it backwards compatible. 

Best wishes
Y.

**Comment by srinsoz** [comment] 2024-02-27 10:33
This issue should be fixed now. Could you validate that it solve your issue?

**Comment by Pnaop** [comment] 2024-06-05 09:22
I am experiencing this issue on Ubuntu 20.04 and Ubuntu 18.04.

**Comment by srinsoz** [comment] 2024-06-05 10:16
We have been able to reproduce your issue. We should have a fix very soon.

**Comment by Pnaop** [comment] 2024-06-05 13:29
That's great news. Thanks for the prompt response!

For others running into similar issues, here's how I fixed it in the meantime:

1. Download the YoctoLib.cpp source: [https://www.yoctopuce.com/FR/downloads/YoctoLib.cpp.61199.zip](https://www.yoctopuce.com/FR/downloads/YoctoLib.cpp.61199.zip)
2. Extract it on your machine.
3. Because I am on Linux, I had to run `sudo apt-get install libusb-1.0-0-dev`
4. Then run build.bat or build.sh depending on your platform.
5. Wait for the compiling to be done.
6. Now copy "libyapi.so.1.0.1", rename to "libyapi-amd64.so" and replace the incorrect shared library with it (in my case it was in: `/home/user/project/venv/lib/python3.9/site-packages/yoctopuce/cdll/libyapi-amd64.so` 
_On other platforms, the names and paths will be different._

After that all worked as expected!

**Comment by srinsoz** [comment] 2024-06-08 13:29
Could you validate that the following binaries are working on your computer:
https://www.yoctopuce.com/FR/downloads/YoctoLib.pythonV2.61305.zip

**Comment by Pnaop** [comment] 2024-06-11 06:35
I can confirm this is working on Ubuntu 20.04 after updating libyapi-amd64.so

**Comment by srinsoz** [comment] 2024-06-11 06:43
Ok. We have just officially release the fix.

**Closed by srinsoz** 2024-06-11 06:43 UTC
